services:
  - type: web
    name: eat-picker
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: picker-db
          property: connectionString

databases:
  - name: picker-db
    ipAllowList: []   # private DB (internal only)
